version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-integration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jjziqtjlibu7"
s3_prefix = "sam-integration"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"sam-tutorial\""
image_repositories = []
disable_rollback = true
