AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - SNS to Lambda

Resources:
  # Define the SNS topic
  AQSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt SNSDispatchFunction.Arn    

  # Provide permission for SNS to invoke the Lambda function
  SNSDispatchFunctionPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref SNSDispatchFunction
      Principal: sns.amazonaws.com

  SNSDispatchRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: StartExecution
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
              states:StartExecution
              logs:CreateLogGroup
              logs:PutLogEvents
            Resources: "*"

  SNSDispatchFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: triggers/sns_dispatch_handler
      Handler: main.handler
      Runtime: python3.9
      Timeout: 3
      MemorySize: 1024
      Role: !GetAtt SNSDispatchRole.Arn
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt DispatcherStateMachine.Arn
      Policies:
      - StepFunctionsStartExecutionPolicy:
          StateMachineName: DispatcherStateMachine

  MongoHandler:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: triggers/mongo_handler
      Handler: main.handler
      Runtime: python3.9
      Timeout: 3
      MemorySize: 1024

  DynamoHandler:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: triggers/dynamo_handler
      Handler: main.handler
      Runtime: python3.9
      Timeout: 3
      MemorySize: 1024

  DispatcherStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: Standard
      DefinitionUri: triggers/state-machine/dispatcher.asl.json
      DefinitionSubstitutions:
        MongoHandlerArn: !GetAtt MongoHandler.Arn
        DynamoHandlerArn: !GetAtt DynamoHandler.Arn

Outputs:
  HelloWorldFunctionOutput:
    Description: SNSDispatchFunction function name
    Value: !Ref SNSDispatchFunction
  
  SNStopicName:
    Description: SNS topic name
    Value: !GetAtt AQSNSTopic.TopicName

  SNStopicARN:
    Description: SNS topic ARN
    Value: !Ref AQSNSTopic